[book]
authors = ["Hongxu Xu"]
description = "Hongxu Xu's personal website"
language = "en"
src = "src"
title = "Hongxu Xu"

[build]
build-dir = "docs"

[output.html]
mathjax-support = true
smart-punctuation = true
cname = "xuhongxu.com"
additional-css = ["style.css"]

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 4